- name: Install Emacs
  homebrew:
    name: emacs
    state: latest

- name: Set config
  file:
    src: "{{ ansible_env.PWD }}/roles/apps/files/emacs"
    path: "~/.emacs"
    state: link

- name: Edit alias
  lineinfile:
    path: ~/.bash_profile
    create: yes
    line: alias e='emacsclient --no-wait'

- name: Make emacs the default editor
  lineinfile:
    path: ~/.bash_profile
    create: yes
    line: export EDITOR=emacsclient
    
    
