- name: Set git config
  file:
    src: "{{ ansible_env.PWD }}/roles/apps/files/{{ item }}"
    path: "~/.{{ item }}"
    state: link
  with_items:
  - gitconfig
  - gitignore_global

- name: Get git-prompt
  get_url:
   url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
   dest: ~/.git-prompt.sh

- name: Git bash settings
  blockinfile:
   path: ~/.bash_profile
   marker: "# {mark} git settings"
   block: |
     # Enable git bash-autocomplete
     [ -f /Library/Developer/CommandLineTools/usr/share/git-core/git-completion.bash ] && . /Library/Developer/CommandLineTools/usr/share/git-core/git-completion.bash
     # Show branch in prompt
     source ~/.git-prompt.sh
     PS1='\W$(__git_ps1 " (\[\e[0;32m%s\e[m\])")\$ '