- name: Install iterm2
  import_role:
    name: tkimball83.iterm2
  vars:
    iterm2_defaults:
    - name: OnlyWhenMoreTabs
      type: string
      value: 0
    - name: PromptOnQuit
      type: bool      
      value: false
