- name: Install MonitorControl
  homebrew_cask:
    name: monitorcontrol
    state: latest

- name: Start spectacle on login
  command: osascript -e 'tell application "System Events" to make login item at end with properties {name:"MonitorControl", path:"/Applications/MonitorControl.app", hidden:false}'
