- name: Configure macOS Dock
  import_role:
    name:  fubarhouse.macdock
  vars:
    dockitems_remove_all: true
    dockitems_enabled:
    - name: Google Chrome
      path: "/Applications/Google Chrome.app"
      pos: 1
    - name: iTerm
      path: "/Applications/iTerm.app"
      pos: 2
    